# Generated by Django 5.1.5 on 2025-01-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingFoodApp', '0003_alter_user_options_alter_review_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
