# Generated by Django 5.1.5 on 2025-01-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingFoodApp', '0005_alter_food_average_rating_alter_store_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
