# Generated by Django 5.1.5 on 2025-01-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingFoodApp', '0008_alter_store_image_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(upload_to='foods/%Y/%m/'),
        ),
    ]
