# Generated by Django 5.1.5 on 2025-02-06 03:33

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingFoodApp', '0009_alter_food_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentvnpay',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='paymentvnpay',
            name='food',
        ),
        migrations.RemoveField(
            model_name='paymentvnpay',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='paymentvnpaydetail',
            name='payment_vnpay',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='paymentvnpaydetail',
            name='food',
        ),
        migrations.RemoveField(
            model_name='paymentvnpaydetail',
            name='menu',
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='BookingFoodApp.order'),
        ),
        migrations.AlterField(
            model_name='store',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, null=True, verbose_name='avatar'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='PaymentVNPay',
        ),
        migrations.DeleteModel(
            name='PaymentVNPayDetail',
        ),
    ]
