# Generated by Django 5.1.5 on 2025-01-23 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingFoodApp', '0002_remove_category_image_alter_comment_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollowedstore',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='BookingFoodApp.store'),
        ),
        migrations.AlterField(
            model_name='userfollowedstore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
