# Generated by Django 5.1.5 on 2025-01-23 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingFoodApp', '0003_alter_userfollowedstore_store_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL),
        ),
    ]
