# Generated by Django 5.1.5 on 2025-01-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingFoodApp', '0004_alter_comment_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
