# Generated by Django 5.1.5 on 2025-01-24 10:57

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingFoodApp', '0004_alter_store_active_alter_store_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='status',
            field=models.CharField(choices=[('available', 'Còn đồ ăn'), ('out_of_stock', 'Hết đồ ăn')], default='out_of_stock', max_length=50),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('review', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review', to='BookingFoodApp.food')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('food', 'user')},
            },
        ),
    ]
